import type { FamilyWorkspace } from "@/lib/domain/types";

export const demoFamilies: FamilyWorkspace[] = [
  {
    id: "fam_chen_household",
    slug: "chen-family",
    familyLabel: "Chen Family",
    legacyStudentName: "Emma Chen",
    parentContactName: "Lydia Chen",
    strategistOwnerId: "demo-strategist-1",
    opsOwnerId: "demo-ops-1",
    strategistOwnerName: "Alicia Wong",
    opsOwnerName: "Narin Chai",
    createdDate: "2025-09-02",
    lastUpdatedDate: "2026-03-09",
    contacts: [
      {
        id: "contact_chen_primary",
        fullName: "Lydia Chen",
        email: "lydia.chen@example.com",
        relationship: "Mother",
        isPrimary: true,
      },
    ],
    students: [
      {
        id: "student_emma_chen",
        familyId: "fam_chen_household",
        familySlug: "chen-family",
        slug: "emma-chen",
        studentName: "Emma Chen",
        gradeLevel: "Grade 11",
        pathway: "us_college",
        tier: "Signature Pathway",
        currentPhase: "Application build",
        overallStatus: "green",
        statusReason:
          "Essay roadmap is locked, spring deadlines are on track, and there are no silent blockers.",
        createdDate: "2025-09-02",
        lastUpdatedDate: "2026-03-09",
        testingProfile: {
          id: "testing_emma",
          currentSat: 1460,
          projectedSat: 1510,
          strategyNote:
            "No retake unless the next practice exam lands below the 1500 range.",
        },
        activities: [
          {
            id: "activity_emma_1",
            activityName: "Robotics Team",
            role: "Build Lead",
            impactSummary: "Leads the prototype team and portfolio documentation.",
            sortOrder: 1,
          },
          {
            id: "activity_emma_2",
            activityName: "Climate Sensors Capstone",
            role: "Founder",
            impactSummary: "Built a climate monitoring prototype with mentor review.",
            sortOrder: 2,
          },
        ],
        competitions: [
          {
            id: "competition_emma_1",
            competitionName: "World Scholar's Cup",
            result: "Regional gold medals",
            yearLabel: "2025",
            sortOrder: 1,
          },
        ],
        schoolTargets: [
          {
            id: "school_emma_1",
            schoolName: "MIT",
            country: "US",
            bucket: "reach",
            fitNote: "Strong if portfolio evidence sharpens.",
            sortOrder: 1,
          },
          {
            id: "school_emma_2",
            schoolName: "Northwestern",
            country: "US",
            bucket: "target",
            fitNote: "Competitive with current testing range.",
            sortOrder: 2,
          },
          {
            id: "school_emma_3",
            schoolName: "Boston University",
            country: "US",
            bucket: "likely",
            fitNote: "Maintain as balance school.",
            sortOrder: 3,
          },
        ],
        monthlySummaries: [
          {
            id: "summary_emma_2026_03",
            studentId: "student_emma_chen",
            reportingMonth: "2026-03-01",
            biggestWin:
              "Emma finalized her personal statement angle around climate-focused engineering and matched it with two new competition results.",
            biggestRisk:
              "The robotics portfolio still needs one cleaner evidence package before April outreach.",
            topNextActions: [
              "Finalize MIT maker portfolio evidence folder",
              "Lock recommender briefing packets",
              "Complete two supplemental essay outlines before March 24",
            ],
            parentVisibleSummary:
              "March is moving well. Emma has a strong story arc in place, tutoring remains aligned to AP Physics and SAT Math priorities, and the immediate focus is packaging her strongest evidence.",
            internalSummaryNotes:
              "No escalation needed. Reinforce why portfolio curation matters more than adding another minor activity.",
          },
          {
            id: "summary_emma_2026_02",
            studentId: "student_emma_chen",
            reportingMonth: "2026-02-01",
            biggestWin:
              "Profile narrative narrowed successfully from general sustainability to engineering systems.",
            biggestRisk: "Teacher recommender timing was still soft in February.",
            topNextActions: [
              "Confirm two recommenders",
              "Review competition reflection write-up",
              "Close SAT retest decision",
            ],
            parentVisibleSummary:
              "February established a sharper application direction and clarified the testing decision.",
            internalSummaryNotes:
              "Needed extra strategist follow-up on recommender ownership.",
          },
        ],
        academicUpdates: [
          {
            id: "acad_emma_1",
            studentId: "student_emma_chen",
            date: "2026-03-07",
            subjectPriority: "AP Physics C and AP Calculus BC",
            gradeOrPredictedTrend:
              "Stable A / A- trend with improved problem-set consistency",
            tutoringStatus: "Weekly physics and math support is on schedule",
            tutorNoteSummary:
              "Emma is now solving multi-step mechanics questions faster and can explain method choice with less prompting.",
            testPrepStatus: "SAT Math maintenance only",
            parentVisible: true,
          },
        ],
        profileUpdates: [
          {
            id: "profile_emma_1",
            studentId: "student_emma_chen",
            date: "2026-03-05",
            projectName: "Urban Climate Sensors capstone",
            milestoneStatus: "Prototype dashboard finalized; mentor review scheduled",
            evidenceAdded:
              "Prototype screenshots, one user-feedback memo, revised technical summary",
            mentorNoteSummary:
              "The project now shows measurable iteration instead of just concept framing.",
            parentVisible: true,
          },
        ],
        tasks: [
          {
            id: "task_emma_1",
            studentId: "student_emma_chen",
            itemName: "MIT maker portfolio evidence folder",
            category: "application",
            owner: "Emma Chen + Alicia Wong",
            dueDate: "2026-03-18",
            status: "in_progress",
            dependencyNotes: "Need final captioning on two project photos.",
            parentVisible: true,
          },
          {
            id: "task_emma_2",
            studentId: "student_emma_chen",
            itemName: "Recommender briefing packet",
            category: "application",
            owner: "Alicia Wong",
            dueDate: "2026-03-14",
            status: "in_progress",
            dependencyNotes: "Waiting on latest activity list formatting.",
            parentVisible: false,
          },
        ],
        decisionLogItems: [
          {
            id: "decision_emma_1",
            studentId: "student_emma_chen",
            date: "2026-03-02",
            decisionType: "Testing",
            summary:
              "No additional SAT retake unless March practice score drops below target range.",
            owner: "Alicia Wong",
            pendingFamilyInput: false,
            status: "resolved",
            parentVisible: true,
          },
        ],
        notes: [
          {
            id: "note_emma_1",
            studentId: "student_emma_chen",
            date: "2026-03-08",
            authorRole: "strategist",
            noteType: "meeting_recap",
            summary: "Monthly strategy review completed",
            body:
              "Parent alignment was strong. Emma understands the difference between flagship evidence and filler activities.",
            visibility: "parent",
          },
        ],
        artifactLinks: [
          {
            id: "artifact_emma_1",
            studentId: "student_emma_chen",
            artifactName: "Emma Chen master drive folder",
            artifactType: "drive_folder",
            linkUrl: "https://drive.google.com/drive/folders/example-emma-master",
            uploadDate: "2026-03-01",
            owner: "Narin Chai",
            parentVisible: true,
          },
        ],
      },
      {
        id: "student_lucas_chen",
        familyId: "fam_chen_household",
        familySlug: "chen-family",
        slug: "lucas-chen",
        studentName: "Lucas Chen",
        gradeLevel: "Grade 9",
        pathway: "us_boarding",
        tier: "Foundation Pathway",
        currentPhase: "Profile build",
        overallStatus: "yellow",
        statusReason:
          "Early positioning is promising, but testing and activity depth still need clearer structure.",
        createdDate: "2026-01-10",
        lastUpdatedDate: "2026-03-06",
        testingProfile: {
          id: "testing_lucas",
          currentSat: undefined,
          projectedSat: undefined,
          currentAct: undefined,
          projectedAct: undefined,
          strategyNote: "SSAT diagnostic scheduled; keep prep exploratory for now.",
        },
        activities: [
          {
            id: "activity_lucas_1",
            activityName: "Debate Club",
            role: "Member",
            impactSummary: "Shows early verbal confidence and coachability.",
            sortOrder: 1,
          },
        ],
        competitions: [],
        schoolTargets: [
          {
            id: "school_lucas_1",
            schoolName: "Choate",
            country: "US",
            bucket: "reach",
            fitNote: "Needs stronger evidence of sustained leadership.",
            sortOrder: 1,
          },
          {
            id: "school_lucas_2",
            schoolName: "Taft",
            country: "US",
            bucket: "target",
            fitNote: "Good fit once testing baseline is clearer.",
            sortOrder: 2,
          },
        ],
        monthlySummaries: [
          {
            id: "summary_lucas_2026_03",
            studentId: "student_lucas_chen",
            reportingMonth: "2026-03-01",
            biggestWin:
              "Lucas now has a credible early boarding-school shortlist and one teacher champion.",
            biggestRisk:
              "Without a testing baseline and clearer activity cadence, the shortlist still feels fragile.",
            topNextActions: [
              "Book SSAT diagnostic",
              "Choose one flagship enrichment lane",
              "Build spring visit plan",
            ],
            parentVisibleSummary:
              "Lucas is in a healthy exploration phase, but the next step is moving from broad options into a more disciplined early plan.",
            internalSummaryNotes:
              "Keep the family from over-expanding the school list before the testing baseline exists.",
          },
        ],
        academicUpdates: [],
        profileUpdates: [],
        tasks: [
          {
            id: "task_lucas_1",
            studentId: "student_lucas_chen",
            itemName: "Book SSAT diagnostic",
            category: "testing",
            owner: "Lydia Chen",
            dueDate: "2026-03-20",
            status: "not_started",
            dependencyNotes: "Need weekend slot confirmation.",
            parentVisible: true,
          },
        ],
        decisionLogItems: [],
        notes: [],
        artifactLinks: [],
      },
    ],
    monthlySummaries: [],
    academicUpdates: [],
    profileUpdates: [],
    tasks: [],
    decisionLogItems: [
      {
        id: "decision_chen_family_1",
        date: "2026-03-06",
        decisionType: "Summer planning",
        summary:
          "Family to confirm whether Emma accepts the climate lab placement by March 20.",
        owner: "Lydia Chen",
        pendingFamilyInput: true,
        status: "pending",
        parentVisible: true,
      },
    ],
    notes: [
      {
        id: "note_chen_family_1",
        date: "2026-03-09",
        authorRole: "ops",
        noteType: "family_coordination",
        summary: "Sibling scheduling reviewed",
        body: "Family wants both student workstreams summarized in one monthly call.",
        visibility: "internal",
      },
    ],
    artifactLinks: [
      {
        id: "artifact_chen_family_1",
        artifactName: "Shared household planning folder",
        artifactType: "drive_folder",
        linkUrl: "https://drive.google.com/drive/folders/example-chen-household",
        uploadDate: "2026-03-01",
        owner: "Narin Chai",
        parentVisible: true,
      },
    ],
    collegeStrategyProfile: {
      id: "college_strategy_chen",
      familyId: "fam_chen_household",
      currentSat: 1460,
      projectedSat: 1510,
      intendedMajorCodes: ["1409", "1101"],
      intendedMajorLabels: ["Civil Engineering", "Computer and Information Sciences, General"],
      strategyNote: "Use Emma as the primary US-college applicant for the workbench in v1.",
    },
    collegeLists: [
      {
        id: "college_list_chen_current",
        familyId: "fam_chen_household",
        listName: "Emma Spring List",
        isCurrent: true,
        createdBy: "demo-strategist-1",
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-09T08:30:00Z",
        items: [
          {
            id: "college_list_item_chen_1",
            familyCollegeListId: "college_list_chen_current",
            scorecardSchoolId: 166683,
            schoolName: "Massachusetts Institute of Technology",
            city: "Cambridge",
            state: "MA",
            ownership: "Private nonprofit",
            studentSize: 11616,
            admissionRate: 0.043,
            satAverage: 1545,
            completionRate: 0.966,
            retentionRate: 0.987,
            averageNetPrice: 20232,
            medianEarnings: 122300,
            matchedProgramCodes: ["1409"],
            matchedProgramLabels: ["Civil Engineering"],
            bucket: "reach",
            bucketSource: "system",
            fitScore: 84,
            fitRationale: "Projected SAT is close to MIT's band and program match is strong, but selectivity keeps it in reach.",
            counselorNote: "Keep only if maker portfolio evidence lands cleanly by April.",
            sortOrder: 1,
          },
          {
            id: "college_list_item_chen_2",
            familyCollegeListId: "college_list_chen_current",
            scorecardSchoolId: 167358,
            schoolName: "Northeastern University",
            city: "Boston",
            state: "MA",
            ownership: "Private nonprofit",
            studentSize: 30742,
            admissionRate: 0.067,
            satAverage: 1499,
            completionRate: 0.913,
            retentionRate: 0.969,
            averageNetPrice: 39322,
            medianEarnings: 84735,
            matchedProgramCodes: ["1101"],
            matchedProgramLabels: ["Computer and Information Sciences, General"],
            bucket: "target",
            bucketSource: "counselor",
            fitScore: 88,
            fitRationale: "Projected testing aligns well and the career-outcomes profile is strong.",
            counselorNote: "Use as a presentable target anchor in the family-facing list.",
            sortOrder: 2,
          },
        ],
      },
    ],
  },
  {
    id: "fam_rattanachai_household",
    slug: "rattanachai-family",
    familyLabel: "Rattanachai Family",
    legacyStudentName: "Nathan Rattanachai",
    parentContactName: "Suda Rattanachai",
    strategistOwnerId: "demo-strategist-1",
    opsOwnerId: "demo-ops-1",
    strategistOwnerName: "Alicia Wong",
    opsOwnerName: "Narin Chai",
    createdDate: "2025-10-01",
    lastUpdatedDate: "2026-03-08",
    contacts: [
      {
        id: "contact_rattanachai_primary",
        fullName: "Suda Rattanachai",
        email: "suda.rattanachai@example.com",
        relationship: "Mother",
        isPrimary: true,
      },
    ],
    students: [
      {
        id: "student_nathan_rattanachai",
        familyId: "fam_rattanachai_household",
        familySlug: "rattanachai-family",
        slug: "nathan-rattanachai",
        studentName: "Nathan Rattanachai",
        gradeLevel: "Grade 11",
        pathway: "us_college",
        tier: "Core Pathway",
        currentPhase: "Profile build",
        overallStatus: "yellow",
        statusReason:
          "Academic momentum is fine, but summer positioning is still unresolved and one term project is behind.",
        createdDate: "2025-10-01",
        lastUpdatedDate: "2026-03-08",
        testingProfile: {
          id: "testing_nathan",
          currentAct: 28,
          projectedAct: 31,
          strategyNote: "ACT diagnostic deferred until AP Statistics consistency improves.",
        },
        activities: [
          {
            id: "activity_nathan_1",
            activityName: "Economics Research Brief",
            role: "Lead researcher",
            impactSummary: "Developing a Bangkok traffic microeconomics brief.",
            sortOrder: 1,
          },
        ],
        competitions: [],
        schoolTargets: [
          {
            id: "school_nathan_1",
            schoolName: "NYU",
            country: "US",
            bucket: "target",
            fitNote: "Good fit if writing depth continues improving.",
            sortOrder: 1,
          },
          {
            id: "school_nathan_2",
            schoolName: "Boston University",
            country: "US",
            bucket: "likely",
            fitNote: "Useful balance school while profile strengthens.",
            sortOrder: 2,
          },
        ],
        monthlySummaries: [
          {
            id: "summary_nathan_2026_03",
            studentId: "student_nathan_rattanachai",
            reportingMonth: "2026-03-01",
            biggestWin:
              "Nathan’s economics research question is now clear and tutor support has stabilized AP Statistics execution.",
            biggestRisk:
              "The summer program decision is lagging and could compress application positioning later.",
            topNextActions: [
              "Finalize economics summer shortlist",
              "Submit term project abstract",
              "Lock AP Statistics remediation plan",
            ],
            parentVisibleSummary:
              "Nathan has a clearer academic lane, but the next two weeks matter because the summer plan needs to move from options to commitment.",
            internalSummaryNotes:
              "Push for a decision meeting, not another open-ended brainstorm.",
          },
        ],
        academicUpdates: [
          {
            id: "acad_nathan_1",
            studentId: "student_nathan_rattanachai",
            date: "2026-03-04",
            subjectPriority: "AP Statistics and economics writing",
            gradeOrPredictedTrend: "B+ moving toward A- with recent quiz improvement",
            tutoringStatus: "Twice-weekly statistics sessions active",
            tutorNoteSummary:
              "Nathan now catches setup errors earlier, but written explanations still need tighter structure.",
            testPrepStatus: "ACT diagnostic deferred",
            parentVisible: true,
          },
        ],
        profileUpdates: [
          {
            id: "profile_nathan_1",
            studentId: "student_nathan_rattanachai",
            date: "2026-03-03",
            projectName: "Bangkok traffic microeconomics brief",
            milestoneStatus: "Abstract drafted; evidence collection behind target",
            evidenceAdded: "One outline and source list",
            mentorNoteSummary:
              "The idea is promising but still too abstract without a sharper data approach.",
            parentVisible: true,
          },
        ],
        tasks: [
          {
            id: "task_nathan_1",
            studentId: "student_nathan_rattanachai",
            itemName: "ACT diagnostic booking",
            category: "testing",
            owner: "Suda Rattanachai",
            dueDate: "2026-03-02",
            status: "in_progress",
            dependencyNotes: "Still waiting for Saturday tutor availability.",
            parentVisible: true,
          },
          {
            id: "task_nathan_2",
            studentId: "student_nathan_rattanachai",
            itemName: "Summer shortlist decision memo",
            category: "application",
            owner: "Alicia Wong",
            dueDate: "2026-03-16",
            status: "not_started",
            dependencyNotes: "Need parent call to narrow final two options.",
            parentVisible: false,
          },
        ],
        decisionLogItems: [],
        notes: [],
        artifactLinks: [],
      },
    ],
    monthlySummaries: [],
    academicUpdates: [],
    profileUpdates: [],
    tasks: [],
    decisionLogItems: [],
    notes: [],
    artifactLinks: [],
    collegeStrategyProfile: {
      id: "college_strategy_rattanachai",
      familyId: "fam_rattanachai_household",
      currentAct: 28,
      projectedAct: 31,
      intendedMajorCodes: ["4506", "5214"],
      intendedMajorLabels: ["Economics", "Marketing/Marketing Management, General"],
      strategyNote: "Use ACT until SAT data exists; cost stays informational in v1.",
    },
    collegeLists: [
      {
        id: "college_list_rattanachai_current",
        familyId: "fam_rattanachai_household",
        listName: "Nathan Initial List",
        isCurrent: true,
        createdBy: "demo-strategist-1",
        createdAt: "2026-03-03T10:00:00Z",
        updatedAt: "2026-03-08T09:30:00Z",
        items: [
          {
            id: "college_list_item_rattanachai_1",
            familyCollegeListId: "college_list_rattanachai_current",
            scorecardSchoolId: 193900,
            schoolName: "New York University",
            city: "New York",
            state: "NY",
            ownership: "Private nonprofit",
            studentSize: 28772,
            admissionRate: 0.121,
            satAverage: 1511,
            completionRate: 0.857,
            retentionRate: 0.942,
            averageNetPrice: 45982,
            medianEarnings: 79302,
            matchedProgramCodes: ["4506"],
            matchedProgramLabels: ["Economics"],
            bucket: "target",
            bucketSource: "system",
            fitScore: 79,
            fitRationale: "Projected ACT supports a plausible target if the research brief sharpens.",
            counselorNote: "Cost remains the main watchpoint.",
            sortOrder: 1,
          },
        ],
      },
    ],
  },
  {
    id: "fam_singh_household",
    slug: "singh-family",
    familyLabel: "Singh Family",
    legacyStudentName: "Priya Singh",
    parentContactName: "Rhea Singh",
    strategistOwnerId: "demo-strategist-2",
    opsOwnerId: "demo-ops-1",
    strategistOwnerName: "Mina Patel",
    opsOwnerName: "Narin Chai",
    createdDate: "2025-12-11",
    lastUpdatedDate: "2026-03-10",
    contacts: [
      {
        id: "contact_singh_primary",
        fullName: "Rhea Singh",
        email: "rhea.singh@example.com",
        relationship: "Mother",
        isPrimary: true,
      },
    ],
    students: [
      {
        id: "student_priya_singh",
        familyId: "fam_singh_household",
        familySlug: "singh-family",
        slug: "priya-singh",
        studentName: "Priya Singh",
        gradeLevel: "Grade 12",
        pathway: "us_college",
        tier: "Application Intensive",
        currentPhase: "Application recovery",
        overallStatus: "red",
        statusReason:
          "Two critical deadlines slipped, recommenders are not fully aligned, and the family has not confirmed the revised application scope.",
        createdDate: "2025-12-11",
        lastUpdatedDate: "2026-03-10",
        testingProfile: {
          id: "testing_priya",
          currentSat: 1380,
          projectedSat: 1430,
          strategyNote:
            "Use current testing as planning baseline; focus more on narrative clarity than another aggressive retake.",
        },
        activities: [
          {
            id: "activity_priya_1",
            activityName: "Portfolio Design Studio",
            role: "Lead designer",
            impactSummary: "Needs stronger evidence packaging before submission.",
            sortOrder: 1,
          },
        ],
        competitions: [
          {
            id: "competition_priya_1",
            competitionName: "Oxbridge Essay Competition",
            result: "Shortlisted",
            yearLabel: "2025",
            sortOrder: 1,
          },
        ],
        schoolTargets: [
          {
            id: "school_priya_1",
            schoolName: "Parsons",
            country: "US",
            bucket: "target",
            fitNote: "Keep if portfolio recovery continues.",
            sortOrder: 1,
          },
          {
            id: "school_priya_2",
            schoolName: "Pratt",
            country: "US",
            bucket: "likely",
            fitNote: "Important balance choice while deadlines recover.",
            sortOrder: 2,
          },
        ],
        monthlySummaries: [
          {
            id: "summary_priya_2026_03",
            studentId: "student_priya_singh",
            reportingMonth: "2026-03-01",
            biggestWin:
              "Priya’s revised school list is now academically coherent after removing unrealistic reaches.",
            biggestRisk:
              "Recommendation packet and portfolio evidence are both behind, creating deadline compression immediately.",
            topNextActions: [
              "Approve revised school list by March 11",
              "Send recommender briefing packet",
              "Recover missed design portfolio milestones",
            ],
            parentVisibleSummary:
              "This is a recovery month. The school list is stronger, but a few delayed inputs now need quick decisions so Priya can move forward without further compression.",
            internalSummaryNotes:
              "Escalate if list approval or packet dispatch slips again.",
          },
        ],
        academicUpdates: [],
        profileUpdates: [
          {
            id: "profile_priya_1",
            studentId: "student_priya_singh",
            date: "2026-03-04",
            projectName: "Design portfolio",
            milestoneStatus: "Evidence package behind target",
            evidenceAdded: "Revised portfolio outline only",
            mentorNoteSummary:
              "Quality is promising, but the portfolio still lacks enough polished proof points.",
            parentVisible: true,
          },
        ],
        tasks: [
          {
            id: "task_priya_1",
            studentId: "student_priya_singh",
            itemName: "Approve revised school list",
            category: "application",
            owner: "Rhea Singh",
            dueDate: "2026-03-11",
            status: "not_started",
            dependencyNotes:
              "Needs final family sign-off before essay allocation is locked.",
            parentVisible: true,
          },
          {
            id: "task_priya_2",
            studentId: "student_priya_singh",
            itemName: "Send recommender briefing packet",
            category: "application",
            owner: "Mina Patel",
            dueDate: "2026-03-07",
            status: "blocked",
            dependencyNotes: "Waiting on the family to confirm school scope.",
            parentVisible: false,
          },
        ],
        decisionLogItems: [
          {
            id: "decision_priya_1",
            studentId: "student_priya_singh",
            date: "2026-03-08",
            decisionType: "School list",
            summary:
              "Family must approve the reduced school list so supplement sequencing can be rebuilt.",
            owner: "Rhea Singh",
            pendingFamilyInput: true,
            status: "pending",
            parentVisible: true,
          },
        ],
        notes: [
          {
            id: "note_priya_1",
            studentId: "student_priya_singh",
            date: "2026-03-09",
            authorRole: "mentor_input",
            noteType: "portfolio_review",
            summary: "Portfolio evidence still thin",
            body:
              "The strongest concept is there, but the proof set still feels incomplete against the current target list.",
            visibility: "internal",
          },
        ],
        artifactLinks: [
          {
            id: "artifact_priya_1",
            studentId: "student_priya_singh",
            artifactName: "Internal school list v3",
            artifactType: "sheet",
            linkUrl: "https://docs.google.com/spreadsheets/d/example-priya-school-list",
            uploadDate: "2026-03-07",
            owner: "Mina Patel",
            parentVisible: false,
          },
        ],
      },
    ],
    monthlySummaries: [],
    academicUpdates: [],
    profileUpdates: [],
    tasks: [],
    decisionLogItems: [],
    notes: [],
    artifactLinks: [],
    collegeStrategyProfile: {
      id: "college_strategy_singh",
      familyId: "fam_singh_household",
      currentSat: 1410,
      projectedSat: 1490,
      intendedMajorCodes: ["5004", "0909"],
      intendedMajorLabels: ["Design and Applied Arts", "Public Relations, Advertising, and Applied Communication"],
      strategyNote: "Protect list balance while portfolio recovery work is still ongoing.",
    },
    collegeLists: [
      {
        id: "college_list_singh_current",
        familyId: "fam_singh_household",
        listName: "Priya Revised List",
        isCurrent: true,
        createdBy: "demo-strategist-2",
        createdAt: "2026-03-07T11:00:00Z",
        updatedAt: "2026-03-10T08:15:00Z",
        items: [
          {
            id: "college_list_item_singh_1",
            familyCollegeListId: "college_list_singh_current",
            scorecardSchoolId: 190150,
            schoolName: "Boston University",
            city: "Boston",
            state: "MA",
            ownership: "Private nonprofit",
            studentSize: 37823,
            admissionRate: 0.141,
            satAverage: 1450,
            completionRate: 0.889,
            retentionRate: 0.931,
            averageNetPrice: 31458,
            medianEarnings: 74425,
            matchedProgramCodes: ["0909"],
            matchedProgramLabels: ["Public Relations, Advertising, and Applied Communication"],
            bucket: "target",
            bucketSource: "counselor",
            fitScore: 86,
            fitRationale: "Projected SAT and urban program fit make BU a stable target in the revised list.",
            counselorNote: "Keep visible as a parent-facing confidence builder.",
            sortOrder: 1,
          },
        ],
      },
    ],
  },
];
